### ISSUE TITLE
Database Error (dev branch)

### ISSUE THREAD

**Issue by crunchprank** [Clidus/gwl#67]
I'm back! My apologies for all the reports. But on the dev branch I noticed that any time when browsing to a game page (e.g. domain.com/game/1234) that I get the following database error:

```
A Database Error Occurred

Error Number: 1054

Unknown column 'StatusNameShort' in 'field list'

SELECT `users`.`UserID`, `UserName`, `ProfileImage`, `StatusNameShort`, `StatusStyle` FROM (`games`) JOIN `collections` ON `games`.`GameID` = `collections`.`GameID` JOIN `users` ON `collections`.`UserID` = `users`.`UserID` JOIN `gameStatuses` ON `gameStatuses`.`StatusID` = `collections`.`StatusID` LEFT JOIN `following` ON `following`.`ChildUserID` = `collections`.`UserID` AND following.ParentUserID = 1 WHERE `users`.`UserID` != '1' AND `games`.`GBID` = '9249' ORDER BY `Ranking` asc, `following`.`ParentUserID` desc

Filename: /home/user/domains/domain.com/public_html/dev/models/game.php

Line Number: 718
```
The above error refers to the "Filename" working directory, however it's true path is:
`/home/cmx/domains/crunch.mx/public_html/dev/ignition_application/models/game.php`
Not sure if that would contribute to the problem but just thought I'd mention it.

The master branch looks fine: http://i.imgur.com/R8gmdn2.png
Screen grab of dev branch: http://i.imgur.com/pvpAy1e.png

**Comment by Clidus** [comment]
My bad, forgot to update database.txt. 

I've checked all the table structures, so they should all be correct now.

**Comment by Clidus** [comment]
And no apologies, please keep them coming :)
