### ISSUE TITLE
Change Default Timestamp

### ISSUE THREAD

**Issue by crunchprank** [Clidus/gwl#70]
By default (a user that is not logged in to change the timestamp to whatever they want) sees the activity feed as this: `8th July, 2015 @347 .beats`. Instead of `beats`, how would I change this to a standard time (e.g. 03:08PM)

**Comment by Clidus** [comment]
Hah, you're going to hate me, but .beats is a bit of an inside joke. I find the entire concept extremely funny, which is why it's (ridiculously) the default timestamp.

Afraid I'm not going to change it :)

**Comment by crunchprank** [comment]
Lol no worries bud :) It's your project and you are allowed to do whatever you want! :P
