### ISSUE TITLE
Error: The Giant Bomb API May Be Down

### ISSUE THREAD

**Issue by crunchprank** [Clidus/gwl#89]
I recently wiped my old GWL install and started from scratch, cloning from the most recent master branch. I didn't face any problems with installation and the site seems to be working fine. However I am running into one odd issue.

Whenever I attempt to add a game to my collection, I am greeted with a pop up box stating that the "Giant Bomb API May Be Down".

This is odd because the API from what I can tell is working fine. As I'm able to search for games and get correct results with no errors. I even made sure to search for games I never had before just to make sure I wasn't looking at cached results.

I also verified that my API key is currently in good standing. On the main Giant Bomb API page, it states:

    Current API Usage
    You have used 13 requests in the last hour for API Path '/search' (reset in 39 minutes)
    Your request rate is fine

I also ran the script from https://github.com/Clidus/gwl/issues/78 and received a valid response (Result: 0000101).

Any ideas on what could be happening?

Thanks!

**Comment by Clidus** [comment]
Hi @crunchprank, which branch did you pull from?

I just wiped my Windows PC, so I'll try to replicate what you did.

**Comment by crunchprank** [comment]
Hey @Clidus. I cloned the master branch. Hope this helps! If you want to test with my key that is fine as well, just let me know and I'll DM you on Twitter.

**Comment by crunchprank** [comment]
Heyo again. I'm just curious, what version of node / npm do you recommend using with this? I ask only because I started from scratch again using a different version of node / npm, and this time I'm still getting an error, but it says "Well shit. Some kind of error gone done happened. Please try again"

I'm not sure if it matters, but for both times I've rebuilt from scratch, I've had an error message pop up on the search page that says this:

```
A PHP Error was encountered
Severity: Warning
Message: curl_setopt_array(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set
Filename: models/utility.php
Line Number: 13
```

I'm not sure if this is the root cause of my problem, but I simply had disabled PHP errors to hide it to begin with.

And in case you're wondering, I do have my open_basedir disabled in my php.ini file:

    open_basedir = none

**Comment by crunchprank** [comment]
@Clidus So you can disregard this issue. My apologies. The whole problem did indeed stem from open_basedir. I've never had a problem with it before, but I disabled it and everything is working fine.
